# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MUsic Technology Online Repository
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /ScienceOfMusic # the subpath of your site, e.g. /blog
url: https://mutor-2.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: mutor-2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
 - _units/_*

collections:
 units:
  output: true

contributors:
 jm:
  fullname: John MacCallum
  email: john.maccallum@hfmt-hamburg.de
  color: "#0000FF"
 gh:
  fullname: Georg Hajdu
  color: "#FF0000"
 pl:
  fullname: Psyche Loui
  color: "#00FF00"
 vg:
  fullname: Victor Gutiérrez
  color: "#9900FF"
 jl:
  fullname: Janina Luckow
  color: "#FF9900"
 fx:
  fullname: Fu Xiao
  color: "#0099FF"

notes: false

# affiliate information used to create the footer.
# these will be processed in order, the top one being placed on the left
affiliates:
 uhh:
  url: "https://www.uni-hamburg.de"
  logo: "assets/images/uhh-logo-web.gif"
  width: "auto"
  height: "76px"
  style: "margin-bottom: -10px"
 mmkh:
  url: "https://www.mmkh.de"
  logo: "assets/images/mmkh_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 neu:
  url: "https://music.neu.edu"
  logo: "assets/images/nu_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 cnmat:
  url: "https://cnmat.berkeley.edu"
  logo: "assets/images/cnmat_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 hoou:
  url: "https://www.hoou.de/institutions/hochschule-fur-musik-und-theater"
  logo: "assets/images/hoou_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 hfmt:
  url: "https://www.hfmt-hamburg.de/start/"
  logo: "assets/images/hfmt_logo_black.png"
  width: "auto"
  height: "80px"
  style: ""