# This is the global config file for this site. All variables set here
# are available throughout the site via the "site" object, for example,
# {{ site.baseurl }}, {{ site.contributors.shortname.email }}, and so on.

# Note that if you are running a local Jekyll server (bundle exec jekyll serve),
# this file will not be reloaded when it is edited--you must restart the server.

title: "MUsic Technology Online Repository : Science Of Music"

email: xiao.fu@hfmt-hamburg.de

description: ""

url: https://mutor-2.github.io

baseurl: /ScienceOfMusic 

# add the names of the contributors to the website here.
# this is for people who actively work on the website, not for authors of units.
# email is optional
# color will be used to color the text of editorial notes (see example-unit.md)
contributors:
 jm:
  fullname: John MacCallum
  email: john.maccallum@hfmt-hamburg.de
  color: "#0000FF"
 gh:
  fullname: Georg Hajdu
  color: "#FF0000"
 pl:
  fullname: Psyche Loui
  color: "#00FF00"
 vg:
  fullname: Victor Gutiérrez
  color: "#9900FF"
 jl:
  fullname: Janina Luckow
  color: "#FF9900"
 fx:
  fullname: Fu Xiao
  color: "#0099FF"

# set this to true or false in order to display or
# hide editorial comments in the text
notes: false

# affiliate information used to create the footer.
# these will be processed in order, the top one being placed on the left
affiliates:
 uhh:
  url: "https://www.uni-hamburg.de"
  logo: "assets/images/uhh-logo-web.gif"
  width: "auto"
  height: "76px"
  style: "margin-bottom: -10px"
 mmkh:
  url: "https://www.mmkh.de"
  logo: "assets/images/mmkh_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 neu:
  url: "https://music.neu.edu"
  logo: "assets/images/nu_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 cnmat:
  url: "https://cnmat.berkeley.edu"
  logo: "assets/images/cnmat_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 hoou:
  url: "https://www.hoou.de/institutions/hochschule-fur-musik-und-theater"
  logo: "assets/images/hoou_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 hfmt:
  url: "https://www.hfmt-hamburg.de/start/"
  logo: "assets/images/hfmt_logo_black.png"
  width: "auto"
  height: "80px"
  style: ""

# add the names of any files you want to appear in the menu.
# the value "units" is a keyword that will cause the units
# submenu to appear in the menu. 
menu:
 - units
 - references.md
 - discussion_questions.md
 - about.md
 - team.md

# these files will be excluded from processing
exclude:
 - _units/*/_*

# add other collections
collections:
 units:
  output: true

# do not change this.
markdown: kramdown